title: Jaewon Yoo

google_analytics: UA-44429056-1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.markdown
 - about.markdown
 - research.markdown
 - teaching.markdown
 - c.v.markdown
 - posts.markdown

# Build settings
markdown: kramdown
theme: minima
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
