title: Jaewon Yoo
author: Contact me at
email: jy3536@nyu.edu
description: # > this means to ignore newlines until "baseurl:"
  # I am an assistant professor at the Institute of Service Science, College of Technology Management, National Tsing Hua University. My research interests lie in the intersection of innovation and marketing.
  # This is my personal home page, where I share and collaborate with my colleagues for my research projects.
  I am an assistant professor at the Institute of Serv. Sci., College of Tech. Mgmt. National Tsing Hua University (國立清華大學). My research interests lie in the intersection of innovation and marketing.
  #TSMC Bldg. R613, 101 Kuang Fu Rd., Hsinchu, Taiwan

twitter_username: j1yoo4
github_username:  j1yoo4
google_analytics: UA-44429056-1

show_excerpts: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.markdown
 - c.v.markdown
 - research.markdown
 - teaching.markdown
 - index.markdown

# Build settings
markdown: kramdown
theme: minima
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
