title: Jaewon Yoo
author: Contact me at
email: j1yoo4@kaist.ac.kr
description: # > this means to ignore newlines until "baseurl:"
  I am a Ph.D. candidate studying quantitative marketing and innovation. This is my personal home page where I share and collaborate with my colleagues for my research projects.
twitter_username: j1yoo4
github_username:  j1yoo4
google_analytics: UA-44429056-1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.markdown
 - research.markdown
 - teaching.markdown
 - c.v.markdown

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:title
