title: Contact me at
author: College of Technology Management
TSMC Building R614
101, Sec. 2, Kuang-Fu Road, Hsinchu 30013
Email: jaewon.yoo@iss.nthu.edu.tw

twitter_username: j1yoo4
github_username:  j1yoo4
google_analytics: UA-44429056-1

show_excerpts: false

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.markdown
 - about.markdown
 - research.markdown
 - teaching.markdown
 - c.v.markdown
 - posts.markdown

# Build settings
markdown: kramdown
theme: minima
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
